### ISSUE TITLE
Practica final-Edwin Ortiz Cruz_4US

### ISSUE THREAD

**Issue by EdwinOrtiz1412** [SistemasTecTlaxiaco/proyecto-final-equipo_buenaonda#2]
[Practica final_4US.pdf](https://github.com/SistemasTecTlaxiaco/proyecto-final-equipo_buenaonda/files/8811577/Practica.final_4US.pdf)

**Comment by Heidi-19** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...felicidades...
