### ISSUE TITLE
ProyectoSistemaBanco-DiegoAlexisCarlosCruz 4°US

### ISSUE THREAD

**Issue by g00gle2401** [SistemasTecTlaxiaco/proyecto-final-equipo_buenaonda#3]
[ProyectoSistemaBanco.pdf](https://github.com/SistemasTecTlaxiaco/proyecto-final-equipo_buenaonda/files/8811622/ProyectoSistemaBanco.pdf)

**Comment by Heidi-19** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...felicidades...
