### ISSUE TITLE
PracticaFinal-Banco_IrvingFernandoReyesPacheco_4US

### ISSUE THREAD

**Issue by IrvingFernand0** [SistemasTecTlaxiaco/proyecto-final-equipo_buenaonda#4]
[Practicafinal-Banco_IrvingFernandoReyesPacheco.pdf](https://github.com/SistemasTecTlaxiaco/proyecto-final-equipo_buenaonda/files/8817860/Practicafinal-Banco_IrvingFernandoReyesPacheco.pdf)

**Comment by Heidi-19** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...felicidades...
